# portainer
# docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
version: "3.3"
services:
  portainer:
    ports:
      - "8000:8000"
      - "9443:9443"
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    image: "portainer/portainer-ee:latest"

  prometheus:
    image: prom/prometheus:latest
    # volumes:
    #   - prometheus_data:/prometheus
    #   - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    # command:
    #   - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    # volumes:
    #   - grafana_data:/var/lib/grafana
    #   - ./grafana/provisioning:/etc/grafana/provisioning
    #   - ./grafana/config.ini:/etc/grafana/config.ini
    #   - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=illchangeitanyway
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - mongodb-data

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
  default:
    name: mongo-express-network

volumes:
  mongodb-data:
    driver: local
  portainer_data: {}
  prometheus_data: {}
  grafana_data: {}
